name: ci cd

on:
  push:
    branches:
      - master

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install dependencies
        run: npm install
      # - name: tests
      #   run: npm test
      - name: build
        run: npm run build
      - name: deploy
        run: |
          npm install -g netlify-cli --force
          netlify deploy --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --dir dist/angular-ci-cd --site=${{secrets.NETLIFY_SITE_ID}} --prod
